image: Visual Studio 2017

environment:
  matrix:
  - Build: mingw32   
    Arch: i686

  - Build: mingw64
    Arch: x86_64
  
  GCC_version: 8.1.0
  

install:
  # https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/
  - appveyor-retry appveyor DownloadFile "https://downloads.sourceforge.net/mingw-w64/%arch%-%GCC_version%-release-win32-sjlj-rt_v6-rev0.7z" -FileName "C:\mingw.7z"
  - set Path=c:\%Build%\bin;%Path%
  - set Path=c:\%Build%\%arch%-w64-mingw32\include;%Path%
  - set Path=c:\%Build%\%arch%-w64-mingw32\lib;%Path%
  - set Path=c:\%Build%\lib\gcc\%arch%-w64-mingw32\%GCC_version%;%Path%
  - set Path=c:\%Build%\libexec\gcc\%arch%-w64-mingw32\%GCC_version%;%Path%
  - 7z x c:\mingw.7z -oc:\

build_script:
  - g++ -v
  - mingw32-make -f Makefile.libretro platform=%Build%

artifacts:
  - path: genesis_plus_gx_libretro.dll
