/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Background_credits_h_
#define _Background_credits_h_
//---------------------------------------------------------------------------------
extern const unsigned char Background_credits[];
extern const int Background_credits_size;
//---------------------------------------------------------------------------------
#endif //_Background_credits_h_
//---------------------------------------------------------------------------------
