/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Banner_top_h_
#define _Banner_top_h_
//---------------------------------------------------------------------------------
extern const unsigned char Banner_top[];
extern const int Banner_top_size;
//---------------------------------------------------------------------------------
#endif //_Banner_top_h_
//---------------------------------------------------------------------------------
