/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Browser_dir_h_
#define _Browser_dir_h_
//---------------------------------------------------------------------------------
extern const unsigned char Browser_dir[];
extern const int Browser_dir_size;
//---------------------------------------------------------------------------------
#endif //_Browser_dir_h_
//---------------------------------------------------------------------------------
