/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Button_down_h_
#define _Button_down_h_
//---------------------------------------------------------------------------------
extern const unsigned char Button_down[];
extern const int Button_down_size;
//---------------------------------------------------------------------------------
#endif //_Button_down_h_
//---------------------------------------------------------------------------------
