/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Button_delete_h_
#define _Button_delete_h_
//---------------------------------------------------------------------------------
extern const unsigned char Button_delete[];
extern const int Button_delete_size;
//---------------------------------------------------------------------------------
#endif //_Button_delete_h_
//---------------------------------------------------------------------------------
