/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Button_icon_h_
#define _Button_icon_h_
//---------------------------------------------------------------------------------
extern const unsigned char Button_icon[];
extern const int Button_icon_size;
//---------------------------------------------------------------------------------
#endif //_Button_icon_h_
//---------------------------------------------------------------------------------
