/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Button_special_h_
#define _Button_special_h_
//---------------------------------------------------------------------------------
extern const unsigned char Button_special[];
extern const int Button_special_size;
//---------------------------------------------------------------------------------
#endif //_Button_special_h_
//---------------------------------------------------------------------------------
