/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Button_icon_sm_h_
#define _Button_icon_sm_h_
//---------------------------------------------------------------------------------
extern const unsigned char Button_icon_sm[];
extern const int Button_icon_sm_size;
//---------------------------------------------------------------------------------
#endif //_Button_icon_sm_h_
//---------------------------------------------------------------------------------
