/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Crosshair_p1_h_
#define _Crosshair_p1_h_
//---------------------------------------------------------------------------------
extern const unsigned char Crosshair_p1[];
extern const int Crosshair_p1_size;
//---------------------------------------------------------------------------------
#endif //_Crosshair_p1_h_
//---------------------------------------------------------------------------------
