/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Crosshair_p2_h_
#define _Crosshair_p2_h_
//---------------------------------------------------------------------------------
extern const unsigned char Crosshair_p2[];
extern const int Crosshair_p2_size;
//---------------------------------------------------------------------------------
#endif //_Crosshair_p2_h_
//---------------------------------------------------------------------------------
