/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Ctrl_justifiers_black_h_
#define _Ctrl_justifiers_black_h_
//---------------------------------------------------------------------------------
extern const unsigned char Ctrl_justifiers_black[];
extern const int Ctrl_justifiers_black_size;
//---------------------------------------------------------------------------------
#endif //_Ctrl_justifiers_black_h_
//---------------------------------------------------------------------------------
