/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Ctrl_4wayplay_h_
#define _Ctrl_4wayplay_h_
//---------------------------------------------------------------------------------
extern const unsigned char Ctrl_4wayplay[];
extern const int Ctrl_4wayplay_size;
//---------------------------------------------------------------------------------
#endif //_Ctrl_4wayplay_h_
//---------------------------------------------------------------------------------
