/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ctrl_nunchuk_h_
#define _ctrl_nunchuk_h_
//---------------------------------------------------------------------------------
extern const unsigned char ctrl_nunchuk[];
extern const int ctrl_nunchuk_size;
//---------------------------------------------------------------------------------
#endif //_ctrl_nunchuk_h_
//---------------------------------------------------------------------------------
