/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ctrl_gamecube_h_
#define _ctrl_gamecube_h_
//---------------------------------------------------------------------------------
extern const unsigned char ctrl_gamecube[];
extern const int ctrl_gamecube_size;
//---------------------------------------------------------------------------------
#endif //_ctrl_gamecube_h_
//---------------------------------------------------------------------------------
