/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Ctrl_teamplayer_h_
#define _Ctrl_teamplayer_h_
//---------------------------------------------------------------------------------
extern const unsigned char Ctrl_teamplayer[];
extern const int Ctrl_teamplayer_size;
//---------------------------------------------------------------------------------
#endif //_Ctrl_teamplayer_h_
//---------------------------------------------------------------------------------
