/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ctrl_classic_h_
#define _ctrl_classic_h_
//---------------------------------------------------------------------------------
extern const unsigned char ctrl_classic[];
extern const int ctrl_classic_size;
//---------------------------------------------------------------------------------
#endif //_ctrl_classic_h_
//---------------------------------------------------------------------------------
