/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Ctrl_mouse_h_
#define _Ctrl_mouse_h_
//---------------------------------------------------------------------------------
extern const unsigned char Ctrl_mouse[];
extern const int Ctrl_mouse_size;
//---------------------------------------------------------------------------------
#endif //_Ctrl_mouse_h_
//---------------------------------------------------------------------------------
