/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Key_trigger_Z_h_
#define _Key_trigger_Z_h_
//---------------------------------------------------------------------------------
extern const unsigned char Key_trigger_Z[];
extern const int Key_trigger_Z_size;
//---------------------------------------------------------------------------------
#endif //_Key_trigger_Z_h_
//---------------------------------------------------------------------------------
