/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Main_options_h_
#define _Main_options_h_
//---------------------------------------------------------------------------------
extern const unsigned char Main_options[];
extern const int Main_options_size;
//---------------------------------------------------------------------------------
#endif //_Main_options_h_
//---------------------------------------------------------------------------------
