/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Option_system_h_
#define _Option_system_h_
//---------------------------------------------------------------------------------
extern const unsigned char Option_system[];
extern const int Option_system_size;
//---------------------------------------------------------------------------------
#endif //_Option_system_h_
//---------------------------------------------------------------------------------
