/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Option_ggenie_h_
#define _Option_ggenie_h_
//---------------------------------------------------------------------------------
extern const unsigned char Option_ggenie[];
extern const int Option_ggenie_size;
//---------------------------------------------------------------------------------
#endif //_Option_ggenie_h_
//---------------------------------------------------------------------------------
