/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Option_sound_h_
#define _Option_sound_h_
//---------------------------------------------------------------------------------
extern const unsigned char Option_sound[];
extern const int Option_sound_size;
//---------------------------------------------------------------------------------
#endif //_Option_sound_h_
//---------------------------------------------------------------------------------
