/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Progress_bar_h_
#define _Progress_bar_h_
//---------------------------------------------------------------------------------
extern const unsigned char Progress_bar[];
extern const int Progress_bar_size;
//---------------------------------------------------------------------------------
#endif //_Progress_bar_h_
//---------------------------------------------------------------------------------
