/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Snap_frame_h_
#define _Snap_frame_h_
//---------------------------------------------------------------------------------
extern const unsigned char Snap_frame[];
extern const int Snap_frame_size;
//---------------------------------------------------------------------------------
#endif //_Snap_frame_h_
//---------------------------------------------------------------------------------
