/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Snap_empty_h_
#define _Snap_empty_h_
//---------------------------------------------------------------------------------
extern const unsigned char Snap_empty[];
extern const int Snap_empty_size;
//---------------------------------------------------------------------------------
#endif //_Snap_empty_h_
//---------------------------------------------------------------------------------
