/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Star_empty_h_
#define _Star_empty_h_
//---------------------------------------------------------------------------------
extern const unsigned char Star_empty[];
extern const int Star_empty_size;
//---------------------------------------------------------------------------------
#endif //_Star_empty_h_
//---------------------------------------------------------------------------------
