/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Background_overlay_h_
#define _Background_overlay_h_
//---------------------------------------------------------------------------------
extern const unsigned char Background_overlay[];
extern const int Background_overlay_size;
//---------------------------------------------------------------------------------
#endif //_Background_overlay_h_
//---------------------------------------------------------------------------------
