/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Background_intro_c3_h_
#define _Background_intro_c3_h_
//---------------------------------------------------------------------------------
extern const unsigned char Background_intro_c3[];
extern const int Background_intro_c3_size;
//---------------------------------------------------------------------------------
#endif //_Background_intro_c3_h_
//---------------------------------------------------------------------------------
