/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Background_main_h_
#define _Background_main_h_
//---------------------------------------------------------------------------------
extern const unsigned char Background_main[];
extern const int Background_main_size;
//---------------------------------------------------------------------------------
#endif //_Background_main_h_
//---------------------------------------------------------------------------------
