/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Background_intro_c4_h_
#define _Background_intro_c4_h_
//---------------------------------------------------------------------------------
extern const unsigned char Background_intro_c4[];
extern const int Background_intro_c4_size;
//---------------------------------------------------------------------------------
#endif //_Background_intro_c4_h_
//---------------------------------------------------------------------------------
