/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Banner_main_h_
#define _Banner_main_h_
//---------------------------------------------------------------------------------
extern const unsigned char Banner_main[];
extern const int Banner_main_size;
//---------------------------------------------------------------------------------
#endif //_Banner_main_h_
//---------------------------------------------------------------------------------
