/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Banner_bottom_h_
#define _Banner_bottom_h_
//---------------------------------------------------------------------------------
extern const unsigned char Banner_bottom[];
extern const int Banner_bottom_size;
//---------------------------------------------------------------------------------
#endif //_Banner_bottom_h_
//---------------------------------------------------------------------------------
