/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Button_text_h_
#define _Button_text_h_
//---------------------------------------------------------------------------------
extern const unsigned char Button_text[];
extern const int Button_text_size;
//---------------------------------------------------------------------------------
#endif //_Button_text_h_
//---------------------------------------------------------------------------------
