/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Button_save_h_
#define _Button_save_h_
//---------------------------------------------------------------------------------
extern const unsigned char Button_save[];
extern const int Button_save_size;
//---------------------------------------------------------------------------------
#endif //_Button_save_h_
//---------------------------------------------------------------------------------
