/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Button_down_over_h_
#define _Button_down_over_h_
//---------------------------------------------------------------------------------
extern const unsigned char Button_down_over[];
extern const int Button_down_over_size;
//---------------------------------------------------------------------------------
#endif //_Button_down_over_h_
//---------------------------------------------------------------------------------
