/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _crosshair-2_h_
#define _crosshair-2_h_
//---------------------------------------------------------------------------------
extern const unsigned char crosshair-2[];
extern const int crosshair-2_size;
//---------------------------------------------------------------------------------
#endif //_crosshair-2_h_
//---------------------------------------------------------------------------------
