/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _crosshair-1_h_
#define _crosshair-1_h_
//---------------------------------------------------------------------------------
extern const unsigned char crosshair-1[];
extern const int crosshair-1_size;
//---------------------------------------------------------------------------------
#endif //_crosshair-1_h_
//---------------------------------------------------------------------------------
