/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Ctrl_menacer_h_
#define _Ctrl_menacer_h_
//---------------------------------------------------------------------------------
extern const unsigned char Ctrl_menacer[];
extern const int Ctrl_menacer_size;
//---------------------------------------------------------------------------------
#endif //_Ctrl_menacer_h_
//---------------------------------------------------------------------------------
