/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Ctrl_gamepad_h_
#define _Ctrl_gamepad_h_
//---------------------------------------------------------------------------------
extern const unsigned char Ctrl_gamepad[];
extern const int Ctrl_gamepad_size;
//---------------------------------------------------------------------------------
#endif //_Ctrl_gamepad_h_
//---------------------------------------------------------------------------------
