/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Ctrl_justifiers_h_
#define _Ctrl_justifiers_h_
//---------------------------------------------------------------------------------
extern const unsigned char Ctrl_justifiers[];
extern const int Ctrl_justifiers_size;
//---------------------------------------------------------------------------------
#endif //_Ctrl_justifiers_h_
//---------------------------------------------------------------------------------
