/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ctrl_wiimote_h_
#define _ctrl_wiimote_h_
//---------------------------------------------------------------------------------
extern const unsigned char ctrl_wiimote[];
extern const int ctrl_wiimote_size;
//---------------------------------------------------------------------------------
#endif //_ctrl_wiimote_h_
//---------------------------------------------------------------------------------
