/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Frame_title_h_
#define _Frame_title_h_
//---------------------------------------------------------------------------------
extern const unsigned char Frame_title[];
extern const int Frame_title_size;
//---------------------------------------------------------------------------------
#endif //_Frame_title_h_
//---------------------------------------------------------------------------------
