/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _generic_point_h_
#define _generic_point_h_
//---------------------------------------------------------------------------------
extern const unsigned char generic_point[];
extern const int generic_point_size;
//---------------------------------------------------------------------------------
#endif //_generic_point_h_
//---------------------------------------------------------------------------------
