/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _generic_openhand_h_
#define _generic_openhand_h_
//---------------------------------------------------------------------------------
extern const unsigned char generic_openhand[];
extern const int generic_openhand_size;
//---------------------------------------------------------------------------------
#endif //_generic_openhand_h_
//---------------------------------------------------------------------------------
