/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Load_recent_h_
#define _Load_recent_h_
//---------------------------------------------------------------------------------
extern const unsigned char Load_recent[];
extern const int Load_recent_size;
//---------------------------------------------------------------------------------
#endif //_Load_recent_h_
//---------------------------------------------------------------------------------
