/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Main_title_h_
#define _Main_title_h_
//---------------------------------------------------------------------------------
extern const unsigned char Main_title[];
extern const int Main_title_size;
//---------------------------------------------------------------------------------
#endif //_Main_title_h_
//---------------------------------------------------------------------------------
