/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Main_reset_h_
#define _Main_reset_h_
//---------------------------------------------------------------------------------
extern const unsigned char Main_reset[];
extern const int Main_reset_size;
//---------------------------------------------------------------------------------
#endif //_Main_reset_h_
//---------------------------------------------------------------------------------
