/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Option_video_h_
#define _Option_video_h_
//---------------------------------------------------------------------------------
extern const unsigned char Option_video[];
extern const int Option_video_size;
//---------------------------------------------------------------------------------
#endif //_Option_video_h_
//---------------------------------------------------------------------------------
