/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Option_ctrl_h_
#define _Option_ctrl_h_
//---------------------------------------------------------------------------------
extern const unsigned char Option_ctrl[];
extern const int Option_ctrl_size;
//---------------------------------------------------------------------------------
#endif //_Option_ctrl_h_
//---------------------------------------------------------------------------------
