/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Overlay_bar_h_
#define _Overlay_bar_h_
//---------------------------------------------------------------------------------
extern const unsigned char Overlay_bar[];
extern const int Overlay_bar_size;
//---------------------------------------------------------------------------------
#endif //_Overlay_bar_h_
//---------------------------------------------------------------------------------
