/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Overlay_item_selected_h_
#define _Overlay_item_selected_h_
//---------------------------------------------------------------------------------
extern const unsigned char Overlay_item_selected[];
extern const int Overlay_item_selected_size;
//---------------------------------------------------------------------------------
#endif //_Overlay_item_selected_h_
//---------------------------------------------------------------------------------
