/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Overlay_item_over_h_
#define _Overlay_item_over_h_
//---------------------------------------------------------------------------------
extern const unsigned char Overlay_item_over[];
extern const int Overlay_item_over_size;
//---------------------------------------------------------------------------------
#endif //_Overlay_item_over_h_
//---------------------------------------------------------------------------------
