/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Sram_empty_h_
#define _Sram_empty_h_
//---------------------------------------------------------------------------------
extern const unsigned char Sram_empty[];
extern const int Sram_empty_size;
//---------------------------------------------------------------------------------
#endif //_Sram_empty_h_
//---------------------------------------------------------------------------------
