/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_select_h_
#define _button_select_h_
//---------------------------------------------------------------------------------
extern unsigned char button_select[];
extern const int button_select_size;
//---------------------------------------------------------------------------------
#endif //_button_select_h_
//---------------------------------------------------------------------------------
