/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_over_h_
#define _button_over_h_
//---------------------------------------------------------------------------------
extern unsigned char button_over[];
extern const int button_over_size;
//---------------------------------------------------------------------------------
#endif //_button_over_h_
//---------------------------------------------------------------------------------
