/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_back_h_
#define _button_back_h_
//---------------------------------------------------------------------------------
extern unsigned char button_back[];
extern const int button_back_size;
//---------------------------------------------------------------------------------
#endif //_button_back_h_
//---------------------------------------------------------------------------------
